### ISSUE TITLE
throw_exception in separate namespace in standalone

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#398]
When exceptions are not disabled, the provided overload of `throw_exception` for standalone should be in the `json::detail` namespace to avoid collisions when linking with other libraries.

**Comment by Appendme** [comment]
What overload of the throw_exception function is used if the library version is higher than 1.73.0?
https://github.com/boostorg/json/blob/develop/include/boost/json/detail/impl/except.ipp#L48
https://github.com/boostorg/json/blob/develop/include/boost/json/detail/impl/except.ipp#L61

**Comment by vinniefalco** [comment]
First of all Boost.JSON is only available in Boost 1.75 and later, the check for BOOST_VERSION is no longer necessary (I put that in there during development, before the first Boost release). Second, `throw_exception` is already provided by Boost unless you disable exceptions by defining `BOOST_NO_EXCEPTIONS`. In this case, you are responsible for providing it.

**Comment by Appendme** [comment]
@vinniefalco I collected the library via vcpkg (windows / static library) and have the following situation:
If I use the library with Boost, I get a link error (there is no boost_json - *.lib in the output files).
If I use it as a standalone library, then I get an error due to the lack of function overloading. (macros BOOST_VERSION set because I use the boost-beast)

In the first situation, there may be a problem with vcpkg.
In the second, it turns out that I cannot use this library if the project uses any other boost library?

**Comment by vinniefalco** [comment]
If you want to use standalone Boost.JSON then you have to define `BOOST_JSON_STANDALONE` when building the library and when the headers are included.

**Comment by vinniefalco** [comment]
I think there is actually a problem with the existing code and the way it checks `BOOST_VERSION`. See: https://github.com/boostorg/json/issues/490

When #490 is fixed, it is possible that it will resolve your issue.

**Comment by grisumbras** [comment]
@Appendme can you check if your issue is resolved in master?

**Comment by Appendme** [comment]
@grisumbras solved.

**Comment by vinniefalco** [comment]
Does _master_ have the fix?

**Comment by Appendme** [comment]
@vinniefalco my project built without errors when using the master branch

**Comment by grisumbras** [comment]
@vinniefalco #492 fixed this issue.

**Comment by vinniefalco** [comment]
Great, thanks!
