### ISSUE TITLE
Link to overloaded function should go to overload landing page

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#425]
When a javadoc contains a link to an overloaded function, for example `@ref finish` in `stream_parser`, the link should take you to the overload resolution page and not the first overload.

**Comment by evanlenz** [comment]
The tricky thing about this one is that the Doxygen output links specifically to that definition. Perhaps that's because Doxygen has no concept of an overload list/resolution page to link to? Should this rule be applied universally (except for in the resolution page itself)? Or might there be exceptions?

**Comment by vinniefalco** [comment]
I can't think of any exceptions

**Comment by evanlenz** [comment]
Should this issue be moved over to the docca project?

**Comment by vinniefalco** [comment]
Yep, I will do that, and I owe you a reproducible test case

**Comment by vinniefalco** [comment]
See https://github.com/boostorg/docca/issues/55
