### ISSUE TITLE
refactor value::to_number

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#548]
We can add a set of private member functions which return the error code enum instead, e.g.:
```
    template<class T>
    T value::to_number_impl( error& e ) const noexcept ->
        typename std::enable_if<
            std::is_signed<T>::value &&
            ! std::is_floating_point<T>::value,
                T>::type;
```

And then re-implement the public overloads of `to_number` in terms of this.

**Comment by pdimov** [comment]
The goal is to decrease the footprint of the function (e.g. https://godbolt.org/z/cWxsf8TdY)

If the error is communicated in `json::error` and an overload of `detail::throw_system_error` is added that takes `json::error` instead of `error_code`, a lot of the error handling paths in the generated code will be simplified because they'll no longer need to repeatedly construct an `error_code`.

**Comment by pdimov** [comment]
E.g. https://godbolt.org/z/vMhTGb6T4
