### ISSUE TITLE
Proposal: Replace ``boost::system::error_*`` with ``std::error_*`` (C++11)

### ISSUE THREAD

**Issue by phprus** [boostorg/json#679]
Boost.JSON requires C++11.

``std::error_code``, ``std::error_category``, ``std::error_condition``, ``std::system_error`` are supported in all compilers required for Boost.JSON.

**Comment by vinniefalco** [comment]
If Boost.Asio permanently switched over, then I might consider it. However, the boost flavors of `error_code`, et. al. are more full-featured than their standard library equivalents. For example, `boost::error_code` is capable of storing the source location where the error was generated. That said, there have been very recent changes to Boost which allow these types to interoperate better with the `std` types. And we are making tweaks to Boost.JSON to let you use the str equivalents more easily. However we can never get rid of the use of `boost` types completely, one because of Asio and two because they have more functionality.

**Comment by phprus** [comment]
Thanks for the answer!
